site_name: SuperBoringPlugins Wiki
theme:
  name: material
  features:
    - content.code.annotate
    - search.suggest
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
  palette:
    scheme: slate
    primary: light blue
    accent: light blue
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/SuperBoringPlugins/Wiki

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SuperBoringPlugins